# Generated by Django 4.0.4 on 2022-04-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
