# Generated by Django 3.2.13 on 2022-04-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_delete_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('estimated_time_to_complete', models.TimeField()),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('total_points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('module_points_acheived', models.IntegerField()),
                ('quiz_points_acheived', models.IntegerField()),
                ('module_status', models.CharField(choices=[('STARTED', 'STARTED'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('UNSEEN', 'UNSEEN')], default='STARTED', max_length=15)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.chapter')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.user')),
            ],
            options={
                'db_table': 'user_modules',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField()),
                ('explanation', models.TextField()),
                ('question', models.TextField()),
                ('correct_option', models.IntegerField()),
                ('options', models.JSONField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.module')),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.module'),
        ),
    ]
